name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image_tag
          path: .

      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
          -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
          -var="ecr_repo=${{ secrets.ECR_REPO }}" \
          -var="image_tag=${IMAGE_TAG}" \
          -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan
